### ISSUE TITLE
Missing information to run locally

### ISSUE THREAD

**Issue by Josehower** [smakosh/next-portfolio-dev#1]
I am trying to use the template but after trying to follow the development steps i can't make it work

![image](https://user-images.githubusercontent.com/61600906/116584034-385ea200-a917-11eb-84a2-0aa4dea5c1d2.png)

Maybe can you please consider update the README.md with more clear setup information. The template is really cool

I already create the reCAPTCHA but i don't know how to fill this
![image](https://user-images.githubusercontent.com/61600906/116584164-5e844200-a917-11eb-99cf-3558bfd331af.png)

do i need a real domain to run the template locally?

wich key do you need secret or public?

i guess is secret but is not specifyed

![image](https://user-images.githubusercontent.com/61600906/116584608-d18db880-a917-11eb-8420-03b04c96acdf.png)

which scopes need the github token?

![image](https://user-images.githubusercontent.com/61600906/116584367-8e334a00-a917-11eb-9a24-f36d974ffcd3.png)

Ty so much in advance

where should i run this command?

`vercel env pull`

**Comment by Josehower** [comment]
After a close look to the code i identifyed an error on the .env.development.local.template

https://github.com/smakosh/next-portfolio-dev/pull/2

**Comment by smakosh** [comment]
🙌🎉
