### ISSUE TITLE
Navigation Issue 

### ISSUE THREAD

**Issue by bharathkalyans** [smakosh/next-portfolio-dev#32]
* The page doesn't scroll to the required section on clicking.
See below for the demo 

https://github.com/smakosh/next-portfolio-dev/assets/49526472/d48fa0d6-cda0-4e5d-b3cd-570309870cc0

**Comment by smakosh** [comment]
Good catch, will investigate and fix

**Comment by smakosh** [comment]
Fix is live, thanks for reporting this issue.
