### ISSUE TITLE
Upgrade to @formspree/react@2.5.0, fix errors

### ISSUE THREAD

**Issue by karlhorky** [smakosh/next-portfolio-dev#35]
Hi @smakosh 👋  hope things are going well!

If you upgrade to [`@formspree/react@2.5.0`](https://github.com/formspree/formspree-js/releases/tag/%40formspree/react%402.5.0), you'll notice some type errors:

```
Error: src/components/modules/Contact/ContactForm/index.tsx(39,26): error TS2339: Property 'forEach' does not exist on type 'SubmissionError<FieldValues>'.
Error: src/components/modules/Contact/ContactForm/index.tsx(39,35): error TS[7](https://github.com/upleveled/next-portfolio-dev/actions/runs/5776672630/job/15656043053?pr=81#step:7:8)006: Parameter 'error' implicitly has an 'any' type.
Error: Process completed with exit code 2.
```

This comes from the `state.errors.forEach` here:

https://github.com/smakosh/next-portfolio-dev/blob/44a9b98bd87da7a95b59248b25ed1eac4189b1cc/src/components/modules/Contact/ContactForm/index.tsx#L39-L41

It seems that Formspree for React changed the data structure for `state.errors`, you can see that now there are two methods: `state.errors.getFieldErrors(field)` and `state.errors.getFormErrors()`:

https://github.com/formspree/formspree-js/commit/49730d9#diff-f43d7a0974df3e96da50460d0688f282e92d327bc53dd39ffc1a79ce16b10b94R18

Also `state.errors.getAllFieldErrors()`, which may be more useful than `getFieldErrors(field)`:

https://github.com/formspree/formspree-js/commit/49730d9#diff-1f9db01dd19d42e313a63f565d5ea2998a592f709e20fa1ec56f4a816f57ebdaR112

**Comment by smakosh** [comment]
Hey @karlhorky, thanks for raising this, will look into it!

**Comment by karlhorky** [comment]
This was our diff to fix it (from https://github.com/upleveled/next-portfolio-dev/pull/81):

```diff
        } finally {
-          if (state.errors.length) {
-            state.errors.forEach((error) => {
-              setFieldError(error.field || 'email', error.message);
+          if (state.errors) {
+            state.errors.getFormErrors().forEach((error) => {
+              setFieldError('email', error.message);
+            });
+
+            state.errors.getAllFieldErrors().forEach(([field, fieldErrors]) => {
+              fieldErrors.forEach((fieldError) => {
+                setFieldError(field, fieldError.message);
+              });
            });
          }
```

**Comment by smakosh** [comment]
Live on `main` branch

**Comment by karlhorky** [comment]
Thanks! Updated in our fork too :)  (sorry for the noise from the incorrect PRs made to this repo)
